# Generated by Django 4.2.7 on 2023-11-21 16:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='fabric',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fabric_image', models.ImageField(upload_to='product_images')),
                ('fabric_title', models.CharField(max_length=255)),
                ('fabric_discription', models.CharField(max_length=255)),
                ('fabric_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('fabric_quantity', models.IntegerField()),
                ('fabric_material', models.CharField(max_length=255)),
            ],
        ),
    ]
